### PR TITLE
Fix the compilation failure

### PR DESCRIPTION
**Pull request by flyrain**
# Description

Fix the error introduced by #59
```
 /app/polaris-core/src/main/java/io/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java:177: error: cannot find symbol
#12 95.94       logger.error("\n\n {} \n\n", overrideMessage);
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by flyrain** [comment]
cc @eric-maynard @MonkeyCanCode

**Comment by MonkeyCanCode** [comment]
LGTM

**Comment by flyrain** [comment]
Hi @aihuaxu, can you take a look? The main is broken now.

**Review by aihuaxu — APPROVED** [review]

**Comment by aihuaxu** [comment]
Thanks @flyrain for the fix.
